/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Deleted { 
    /**
     * Status of delete operationId
     */
    status?: Deleted.StatusEnum;
}
export namespace Deleted {
    export type StatusEnum = 'OK';
    export const StatusEnum = {
        Ok: 'OK' as StatusEnum
    };
}


