/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Privilege } from './privilege';


export interface PagedPrivileges { 
    content?: Array<Privilege>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
}

