/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface PagedUsers { 
    content?: Array<User>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
}

