/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface PagedRoles { 
    content?: Array<Role>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
}

