/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonBody { 
    firstName: string;
    infix?: string;
    lastName: string;
    dateOfBirth?: string;
}

