/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonAdres1 { 
    firstName: string;
    infix?: string;
    lastName: string;
    dateOfBirth?: string;
    adresses?: Array<number>;
    id: number;
}

