/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Standaardformaat (`application/problem+json`) voor probleemdetails in HTTP API\'s (RFC 7807). 
 */
export interface Problem { 
    timestamp?: string;
    /**
     * De HTTP statuscode gegenereerd door de server waar het probleem zich voordoet.
     */
    status?: number;
    error?: string;
    trace?: string;
    message?: string;
    path?: string;
}

