/**
 * Adres API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Privilege } from './privilege';


export interface Role { 
    rolename: string;
    description?: string;
    privileges?: Array<Privilege>;
    id: number;
}

